---
- name: Create a public ip address for VM
  azure_rm_publicipaddress:
    resource_group: "{{ resourcegroup }}"
    name: "{{ vmname }}_pubip"
    allocation_method: static

- name: Create a network interface for VM
  azure_rm_networkinterface:
    name: "{{ vmname }}_nic01"
    resource_group: "{{ resourcegroup }}"
    virtual_network: "{{ virtualnetwork_name }}"
    subnet_name: "{{ subnet_name }}"
    security_group: "{{ networksecuritygroup_name }}"
    ip_configurations:
      - name: "{{ vmname }}_nic01_ipconfig"
        public_ip_address_name: "{{ vmname }}_pubip"
        primary: True

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup }}"
    name: "{{ vmname }}"
    vm_size: "{{ vmsize }}"
    os_type: "{{ ostype }}"
    managed_disk_type: Standard_LRS
    admin_username: '{{ azurevmuser }}'
    admin_password: "{{ azurevmpw }}"
    network_interfaces: "{{ vmname }}_nic01"
    image:
        offer: "{{ offer }}"
        publisher: "{{ publisher }}"
        sku: "{{ sku }}"
        version: "{{ version }}"
    tags:
      ansible: "{{ vmname }}"
      project: "{{ tag_project }}"
      owner: "{{ tag_owner }}"

- name: Create Azure VM extension to enable HTTP WinRM in firewall
  azure_rm_virtualmachineextension:
    name: winrm-extension
    resource_group: "{{ resourcegroup }}"
    virtual_machine_name: "{{ vmname }}"
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: "1.9"
    settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass {{ powershell }}"}'
    auto_upgrade_minor_version: true
  when: ostype == "Windows"